def ret_subjects():
    return [
            "Algebra",
            "Geometry",
            "Algebra II",
            "Pre-Calculus",
            "Math Analysis",
            "Statistics",
            "Calculus AB",
            "Calculus BC",
            "Linear Algebra",
            "Physics 1",
            "Physics 2",
            "Physics C",
            "Computer Science Principles",
            "Computer Science A",
            "Data Structures",
            "Algorithims",
            "Inorganic Chemistry",
            "Organic Chemistry",
            "Zoology",
            "Human Biology",
            "Biotechnology",
            "Biochemistry",
            "Psychology",
            "English",
            "Creative Writing",
            "Multimodal Literature",
            "Historical Literature",
            "Political Science",
            "American History",
            "European History",
            "Russian History",
            "Asian History",
            "African History",
            "International History",
            "Spanish",
            "French",
            "Japanese",
            ]

def ret_reasons():
    return ["Homework", 
            "Standardized Test (ACT, SAT)",
            "Research",
            "For Fun"]